---
services:
  traefik:
    image: docker.io/library/traefik:v3.4.1
    restart: unless-stopped
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --ping=true
      - --api.insecure=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-authentik-forward-plugin-sandbox
      - --experimental.localPlugins.authentikForwardPlugin.modulename=github.com/xabinapal/traefik-authentik-forward-plugin
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../:/plugins-local/src/github.com/xabinapal/traefik-authentik-forward-plugin:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.service=api@internal

  whoami:
    image: docker.io/traefik/whoami:v1.11.0
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.routers.whoami.middlewares=whoami_stripprefix,whoami_authentikforward
      - traefik.http.middlewares.whoami_stripprefix.stripPrefix.prefixes=/test
      - traefik.http.middlewares.whoami_authentikforward.plugin.authentikForwardPlugin.address=http://akserver:9000
      - traefik.http.middlewares.whoami_authentikforward.plugin.authentikForwardPlugin.unauthorizedStatusCode=401
      - traefik.http.middlewares.whoami_authentikforward.plugin.authentikForwardPlugin.redirectStatusCode=302
      - traefik.http.middlewares.whoami_authentikforward.plugin.authentikForwardPlugin.unauthorizedPaths=^/.*$
      - traefik.http.middlewares.whoami_authentikforward.plugin.authentikForwardPlugin.redirectPaths=^/login/?$
