displayName: Traefik Authentik Forward Plugin
type: middleware
iconPath: .assets/icon.png

import: github.com/xabinapal/traefik-authentik-forward-plugin

summary: Traefik plugin to integrate Authentik as a ForwardAuth provider, with enhanced workflow, streamlined configuration, and several bugfixes over the default implementation.

testData:
  address: https://authentik.example.com
  unauthorizedStatusCode: 401
  unauthorizedPathStatusCodes:
    "/test/users": 403
    "/test/users/[0-9]+": 404